language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - qt5-default qttools5-dev-tools cmake openssl

before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt562-trusty --yes; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --yes qt56base ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt56/bin/qt56-env.sh ; fi
- qmake -v

script:
- qmake
- make
